### ISSUE TITLE
我觉得作者可以做这样一个实现

### ISSUE THREAD

**Issue by 13120241790** [wuapnjie/PuzzleView#1]
## 首先感谢作者无私的分享
其次这类的应用场景 我觉得多见于 类似微信 创建群组后的 默认群头像。群头像都是由群成员头像组拼而成。我觉得作者如果时间充裕可以做这样的 demo 感觉实际应用场景更多，我感觉作者精通此类技术 应该实现起来对你来说相对简单。预祝作者 star 爆棚 工作顺利
👍  Thanks

**Comment by wuapnjie** [comment]
啊哈，好，其实只是想实现Layout for Inatagram的拼图效果才做的，想了好久呢，有时间可以做一下呢。谢谢你的建议。不过我还没工作呢，明年要找实习。
