### ISSUE TITLE
编辑点击图片事件。

### ISSUE THREAD

**Issue by NicodeLee** [wuapnjie/PuzzleView#14]
我这边的UI要求点击图片弹出操作菜单做旋转这些操作。
浏览了下，好像已经有onPieceSelected没有实现。
还是已经有我没注意到，再烦请。

**Comment by wuapnjie** [comment]
额，竟然没有实现，失误，中午有时间我加上

**Comment by NicodeLee** [comment]
嗯，试过可以了，那等你的更新吧。
