### ISSUE TITLE
ProcessActivity photo is in different order in contrast to compiled photo in MainActivity. 

### ISSUE THREAD

**Issue by arkinaforlife** [wuapnjie/PuzzleView#16]
Hi,

When i selected multiple photos in mainactivity everything works fine, but when i choose one of the created layouts above the photo order is different in the processactivity. For example if  i select 7 images, the layouts above are created and photo 1 is above and photo 7 is below. This order is differently in processactivity. This happens not always, you have to try a few different combinaties to reproduce this bug.
[
![screenshot_2017-05-08-15-05-08](https://cloud.githubusercontent.com/assets/7904887/25805483/202674d2-3400-11e7-975b-041676e6356a.png)
![screenshot_2017-05-08-15-05-16](https://cloud.githubusercontent.com/assets/7904887/25805484/203b721a-3400-11e7-870e-d3b7f08da6f2.png)

](url)

I hope it's easy to fix. 

Keep up the good work! 

Arkina

**Comment by wuapnjie** [comment]
This demo just tell you how to use this library. The reason is picasso load photo with different speed so that the the list is random. I will fix it soon.
