### ISSUE TITLE
厉害啊

### ISSUE THREAD

**Issue by 13120241790** [wuapnjie/PuzzleView#2]
我也认识一个成都电子科技大学的 我忘了叫什么名字了 对 AIDL 蛮有研究的 http://blog.csdn.net/luoyanglizi/article/details/52029091 这个应该是你同学吧

**Comment by wuapnjie** [comment]
恩，好基友，一个工作室的

AMing <notifications@github.com>于2016年8月25日周四 下午3:02写道：
