### ISSUE TITLE
关于PuzzleView复用的问题

### ISSUE THREAD

**Issue by mtdhllf** [wuapnjie/PuzzleView#25]
PuzzleView复用后，选择其他模板，边界不能拖拽，这个要如何处理~

**Comment by wuapnjie** [comment]
这个复用是指？

2017年12月21日 17:38，"mtdhllf" <notifications@github.com>写道：

PuzzleView复用后，选择其他模板，边界不能拖拽，这个要如何处理~

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wuapnjie/PuzzleView/issues/25>, or mute the thread
