### ISSUE TITLE
如果我就选择一张图进行拼图，现在您这边是生成两张一样的图进行拼图，如果现在想就生成这一张图，怎么处理呢？

### ISSUE THREAD

**Issue by renqingyou** [wuapnjie/PuzzleView#26]
如题
@wuapnjie

**Comment by wuapnjie** [comment]
新建一个Layout继承自PuzzleLayout，onLayout方法什么也不做

2017年12月26日 10:48，"renqingyou" <notifications@github.com>写道：

**Comment by renqingyou** [comment]
我尝试着写，发现不行，PuzzleLayout是接口，很多方法是必须要实现的呀
@wuapnjie  @wuapnjie @wuapnjie

**Comment by wuapnjie** [comment]
我在提供的demo上测试了，可以实现
[image: 内嵌图片 1]


[image: 内嵌图片 3]

2017年12月26日 15:10，"renqingyou" <notifications@github.com>写道：
