### ISSUE TITLE
onSizeChanged 时如何处理才能保持所有的操作效果呢?

### ISSUE THREAD

**Issue by halyfux** [wuapnjie/PuzzleView#32]
大家好, 我遇到这样一个问题 , PuzzleView 在同一个界面布局变化后  进行缩放结果 和 原始的比列有很大偏差, 源码的处理是重置 , 求助,谢谢!

**Comment by wuapnjie** [comment]
把每个piece的matrix值储存，把puzzle layout的状态储存，然后按布局变化做相应的变化。 有个needResetPieceMatrix变量，看看可不可以，不行的话就要自己根据piece的matrix做操作后设置给piece
