### ISSUE TITLE
图片适配逻辑

### ISSUE THREAD

**Issue by AlbertLiu-Breeze** [wuapnjie/PuzzleView#4]
` static Matrix createMatrix(Border border, int width, int height, float extraSize) {
        final RectF rectF = border.getRect();

        Matrix matrix = new Matrix();

        float offsetX = rectF.centerX() - width / 2;
        float offsetY = rectF.centerY() - height / 2;

        matrix.postTranslate(offsetX, offsetY);

        float scale;

        if (width * rectF.height() > rectF.width() * height) {
            scale = (rectF.height() + extraSize) / height;
        } else {
            scale = (rectF.width() + extraSize) / width;
        }

        matrix.postScale(scale, scale, rectF.centerX(), rectF.centerY());

        return matrix;
    }`

里面的if判断逻辑能解释一下么，我感觉有问题

**Comment by wuapnjie** [comment]
这个是生成以那个rect区域的图片以centerCrop形式呈现，你可以查看ImageView里对centerCrop方式的Matrix设置

**Comment by AlbertLiu-Breeze** [comment]
我开始以为是图片等比例缩放，现在没有问题了，可以关了，谢谢
