### ISSUE TITLE
可否实现图片间距?

### ISSUE THREAD

**Issue by onclicklistener** [wuapnjie/PuzzleView#5]
现在如果使用setBorderWidth,border颜色会直接覆盖在图片上面,图片无法展示完全,并且如果设置背景,背景无法透过图片间隔展现出来

**Comment by wuapnjie** [comment]
好的，现在没有加图片间距，不过我会马上加上去的

**Comment by onclicklistener** [comment]
期待,做得真棒

**Comment by wuapnjie** [comment]
现在，对每个PuzzlePiece都可以设置padding，在PuzzleView中重载了许多addPiece()方法，允许padding的设置，具体的代码看最新的demo中的ProcessActivity。同时设置PuzzleView的padding和Piece的padding后效果类似这样，Background设置为了白色。
![](http://7xrqmj.com1.z0.glb.clouddn.com/device-2017-02-15-140818.png?imageView2/2/w/540)

**Comment by onclicklistener** [comment]
已测试,非常好使,我有几个小建议:
1.拖动HandlingLine的时候extra略小,不太好拖动,extra改成60差不多
2.PuzzleView没有返回List<PuzzlePiece>的方法,导致padding只能设置一次,建议返回List<PuzzlePiece>或者给PuzzleView添加setPadding方法
3.selectedBorderWidth我觉得不应该和borderWidth绑定,单独设置更合理一点
4.判断长按的时间现在是1000ms,有点长,手抖就不太容易判定是长按,改成300ms更舒服一些
以上几点是我自己修改了你的代码之后运行测试过的一些优化的小建议,还有一个问题我没想到解决办法,就是设置了padding之后HandlingLine距离图片就有了间隔,这个间隔还没想到办法去掉,你有没有什么好的建议?

**Comment by wuapnjie** [comment]
感谢你提的建议，我有时间会修改的，关于最后你说有了间距，我是觉得这样有间距，放在中间比较好看呢……这次改的匆忙，等有时间了我会提供选择样式的接口的。

**Comment by onclicklistener** [comment]
嗯嗯!做得非常棒,佩服
