### ISSUE TITLE
改变尺寸会出现多余的线

### ISSUE THREAD

**Issue by onclicklistener** [wuapnjie/PuzzleView#6]
比如我刚开始的尺寸是1:1,长这个样子:
![11111](https://cloud.githubusercontent.com/assets/1744780/23644335/db89f32e-0341-11e7-883c-2c5d40dd7cde.jpg)
当我改变它的尺寸为4:3的时候,变成了这个样子:
![22222](https://cloud.githubusercontent.com/assets/1744780/23644355/f312aad6-0341-11e7-8c83-31491c2b55c4.jpg)
出现了多余的分割线
当我再次将它的尺寸变为1:1de的时候,分割线依然存在
![33333](https://cloud.githubusercontent.com/assets/1744780/23644372/0ae81290-0342-11e7-9b4c-4e0a3e61a7be.jpg)

**Comment by onclicklistener** [comment]
经验证,需要在PuzzleView的onSizeChanged方法中将
```
if (mPuzzleLayout != null) {
    mPuzzleLayout.setOuterBorder(mBorderRect);
    mPuzzleLayout.layout();
 }
```
修改为
```
if (mPuzzleLayout != null) {
    mPuzzleLayout.reset();
    mPuzzleLayout.setOuterBorder(mBorderRect);
    mPuzzleLayout.layout();
}
```

**Comment by wuapnjie** [comment]
好的，谢谢提醒😁
