### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by liangnansheng** [wuapnjie/PuzzleView#8]
为什么我的图片Border与调节图片长宽的那条线有空隙

**Comment by wuapnjie** [comment]
可以贴图吗？

**Comment by liangnansheng** [comment]
![img_20170308_113830](https://cloud.githubusercontent.com/assets/20430123/23689190/043e0640-03f4-11e7-8530-cecd0ba336d8.jpg)

请问怎么调节图片与图片中间的那个线  与图片的距离呀？

**Comment by wuapnjie** [comment]
这是新加的padding功能，有个通过setDefaultPiecePadding和setPadding方法控制，你可以查看Demo中ProcessActivity的相关设置，当然你可以都设为0，就是你要的效果了。

**Comment by liangnansheng** [comment]
谢谢，可以给个思路如何实现斜线的吗

**Comment by onclicklistener** [comment]
PuzzleView的onDraw中的
```
canvas.clipRect(border.getRect());
```
换成
```
canvas.clipPath(path);
```
path自己看喽→_→

**Comment by liangnansheng** [comment]
你实现了斜线的吗？

**Comment by onclicklistener** [comment]
你要的不是思路么 @liangnansheng

**Comment by liangnansheng** [comment]
我还在实现中@onclicklistener  遇到了问题
